INSERT INTO products (name, price, image_path) VALUES ("The Shawshank Redemption (1994)", 34.62, "http://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Godfather (1972)", 22.40, "http://imovieshd.net/wp-content/uploads/2014/12/The-Godfather-1972-720p-YIFY.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Godfather: Part II (1974)", 8.69, "http://www.viz4u.net/v3/img/movieposter/actual/The%20Godfather%20Part%20II%20(1974).jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Dark Knight (2008)", 36.20, "http://static.comicvine.com/uploads/original/0/4115/885630-1new_joker_poster_for_the_dark_knight.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Pulp Fiction (1994)", 44.41, "http://upload.wikimedia.org/wikipedia/en/8/82/Pulp_Fiction_cover.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Schindler's List (1993)", 43.89, "http://upload.wikimedia.org/wikipedia/en/3/38/Schindler's_List_movie.jpg");
INSERT INTO products (name, price, image_path) VALUES ("12 Angry Men (1957)", 38.51, "http://upload.wikimedia.org/wikipedia/en/9/91/12_angry_men.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Il buono, il brutto, il cattivo. (1966)", 16.12, "http://dvd.box.sk/newsimg/dvdmov/max1133207043-frontback-cover.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Lord of the Rings: The Return of the King (2003)", 47.28, "http://upload.wikimedia.org/wikipedia/en/9/9d/Lord_of_the_Rings_-_The_Return_of_the_King.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Fight Club (1999)", 46.81, "http://infolab.stanford.edu/~prasanna/dmc/collapse/fightclub.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Lord of the Rings: The Fellowship of the Ring (2001)", 37.57, "http://upload.wikimedia.org/wikipedia/en/0/0c/The_Fellowship_Of_The_Ring.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Star Wars: Episode V - The Empire Strikes Back (1980)", 10.70, "http://i.jeded.com/i/star-wars-episode-v--the-empire-strikes-back.13948.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Forrest Gump (1994)", 23.20, "http://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Inception (2010)", 33.66, "http://www.aceshowbiz.com/images/still/inception_poster16.jpg");
INSERT INTO products (name, price, image_path) VALUES ("One Flew Over the Cuckoo's Nest (1975)", 16.15, "https://lunkiandsika.files.wordpress.com/2011/07/one-flew-over-the-cuckoos-nest-1975-poster-02.png");
INSERT INTO products (name, price, image_path) VALUES ("The Lord of the Rings: The Two Towers (2002)", 36.26, "http://img4.wikia.nocookie.net/__cb20150203041214/lotr/images/9/98/The_two_tower.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Goodfellas (1990)", 24.98, "https://cinesloth.files.wordpress.com/2013/07/goodfellas.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Matrix (1999)", 17.94, "http://horrornews.net/wp-content/uploads/2013/01/Matrix-poster-2-365x500.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Star Wars (1977)", 18.10, "http://www.blastr.com/sites/blastr/files/Star-Wars-Movie-Poster-1977-original.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Shichinin no samurai (1954)", 13.8, "http://www.titrari.ro/moviepics/0047478.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Cidade de Deus (2002)", 43.76, "http://upload.wikimedia.org/wikipedia/en/1/10/CidadedeDeus.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Interstellar (2014)", 19.57, "http://i.imgur.com/1eOaHGR.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Se7en (1995)", 42.23, "http://ia.media-imdb.com/images/M/MV5BMTYzODY2NTY0Ml5BMl5BanBnXkFtZTcwODQyOTkxMQ@@._V1_.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Usual Suspects (1995)", 11.13, "http://upload.wikimedia.org/wikipedia/en/9/9c/Usual_suspects_ver1.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Silence of the Lambs (1991)", 21.83, "http://lipmag.com/wp-content/uploads/2014/07/The-Silence-of-the-Lambs.jpg");
INSERT INTO products (name, price, image_path) VALUES ("It's a Wonderful Life (1946)", 18.0, "http://www.miamijazzsociety.com/wp-content/uploads/2013/11/IAWL.jpg");
INSERT INTO products (name, price, image_path) VALUES ("C'era una volta il West (1968)", 43.87, "http://i.jeded.com/i/once-upon-a-time-in-the-west-cera-una-volta-il-west.11966.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Léon (1994)", 42.20, "http://upload.wikimedia.org/wikipedia/en/0/03/Leon-poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("La vita è bella (1997)", 18.93, "https://files.nyu.edu/shk347/public/Pictures/Lavitaebella.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Casablanca (1942)", 19.49, "http://alluc.be/wp-content/uploads/2015/02/Casablanca-1942.jpg");
INSERT INTO products (name, price, image_path) VALUES ("American History X (1998)", 23.77, "http://www.movieposter.com/posters/archive/main/92/MPW-46054");
INSERT INTO products (name, price, image_path) VALUES ("Raiders of the Lost Ark (1981)", 16.86, "http://trentflix.com/wp-content/uploads/2012/08/142-Indiana-Jones-and-The-Raiders-of-The-Lost-Ark-1981-_2.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Saving Private Ryan (1998)", 32.61, "http://e.movie.as/p/36023.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Sen to Chihiro no Kamikakushi (2001)", 26.72, "http://www51.indowebster.com/b4e8b307969bb0d680a6eba788f6e8ad.jpg");
INSERT INTO products (name, price, image_path) VALUES ("City Lights (1931)", 17.81, "http://www.impawards.com/1931/posters/city_lights.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Psycho (1960)", 39.50, "http://upload.wikimedia.org/wikipedia/en/b/b9/Psycho_(1960).jpg");
INSERT INTO products (name, price, image_path) VALUES ("Rear Window (1954)", 26.81, "http://upload.wikimedia.org/wikipedia/commons/3/38/Rear_Window_film_poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Whiplash (2014)", 40.12, "http://www.washingtonpost.com/express/wp-content/uploads/2014/12/1.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Intouchables (2011)", 17.37, "http://upload.wikimedia.org/wikipedia/en/archive/9/93/20150323061214!The_Intouchables.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Modern Times (1936)", 6.58, "http://upload.wikimedia.org/wikipedia/en/6/6e/Moderntimes.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Terminator 2: Judgment Day (1991)", 22.24, "http://www.nitehawkcinema.com/wp-content/uploads/2014/06/poster-terminator-2-judgment-day-1991-schwarzenegger.png");
INSERT INTO products (name, price, image_path) VALUES ("The Green Mile (1999)", 13.28, "http://upload.wikimedia.org/wikipedia/en/c/ce/Green_mile.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Memento (2000)", 44.24, "http://www.fomindir.in/rsm/upload/big/2014/05/18/53789d7e8d7e1.jpeg");
INSERT INTO products (name, price, image_path) VALUES ("The Pianist (2002)", 44.51, "http://s6.postimg.org/6pq1to5pt/pianist_ver3.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Departed (2006)", 30.57, "http://i.imgur.com/KM3yW.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Gladiator (2000)", 11.46, "http://i.jeded.com/i/gladiator.20893.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Apocalypse Now (1979)", 21.98, "http://www.filmlinks4u.to/wp-content/uploads/2011/04/Apocalypse-Now-1979-%E2%80%93-Hollywood-Movie-Watch-Online.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Sunset Blvd. (1950)", 32.32, "http://upload.wikimedia.org/wikipedia/en/0/0a/SunsetBoulevardfilmposter.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964)", 23.5, "http://upload.wikimedia.org/wikipedia/en/e/e6/Dr._Strangelove_poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Back to the Future (1985)", 42.57, "https://johneaves.files.wordpress.com/2010/07/back-to-the-future-1985.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Alien (1979)", 26.42, "http://upload.wikimedia.org/wikipedia/en/c/c3/Alien_movie_poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Prestige (2006)", 14.55, "http://www.carseywolf.ucsb.edu/sites/www.carseywolf.ucsb.edu/files/the-prestige-cover.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Great Dictator (1940)", 16.28, "http://img13.nnm.me/9/2/d/0/5/6e975d8c6dcabb6711b77957362.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Lion King (1994)", 20.78, "http://posterpress.us/uploads/t/the_lion_king_1994.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Das Leben der Anderen (2006)", 7.14, "https://thefilmelitist.files.wordpress.com/2011/06/das-leben-der-anderen-original1.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Nuovo Cinema Paradiso (1988)", 18.81, "https://files.nyu.edu/shk347/public/Pictures/cinema-paradiso.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Django Unchained (2012)", 18.32, "http://movi.ca/im/mio/movie-Django-Unchained-2012.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Shining (1980)", 19.90, "https://simonsayswatchthis.files.wordpress.com/2013/10/the-shining-dvd-cover-01.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Dark Knight Rises (2012)", 16.98, "http://cdn.collider.com/wp-content/uploads/the-dark-knight-rises-batman-poster1.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Paths of Glory (1957)", 31.74, "http://ecx.images-amazon.com/images/I/51TDZ1EGVPL.jpg");
INSERT INTO products (name, price, image_path) VALUES ("American Beauty (1999)", 41.81, "http://upload.wikimedia.org/wikipedia/en/b/b6/American_Beauty_poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("WALL·E (2008)", 29.41, "http://img1.wikia.nocookie.net/__cb20110309185550/disney/es/images/4/46/Walle.jpg");
INSERT INTO products (name, price, image_path) VALUES ("North by Northwest (1959)", 48.62, "http://the.hitchcock.zone/files/captures/5503_front.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Aliens (1986)", 41.34, "http://vignette4.wikia.nocookie.net/avp/images/e/e0/Aliens_ver1_xlg.PNG/revision/latest?cb=20121205103239");
INSERT INTO products (name, price, image_path) VALUES ("Citizen Kane (1941)", 49.31, "http://upload.wikimedia.org/wikipedia/en/c/ce/Citizenkane.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Vertigo (1958)", 35.13, "http://the.hitchcock.zone/files/gallery/org/5739.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Hotaru no haka (1988)", 23.63, "http://vignette2.wikia.nocookie.net/enanimanga/images/d/dc/Grave_of_the_Fireflies.jpg/revision/latest?cb=20140711121233");
INSERT INTO products (name, price, image_path) VALUES ("Le fabuleux destin d'Amélie Poulain (2001)", 25.66, "http://imageshack.us/a/img99/6686/lefabuleuxdestindamelie.jpg");
INSERT INTO products (name, price, image_path) VALUES ("M (1931)", 25.21, "http://theworldcinemablog.files.wordpress.com/2014/01/m-1.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Das Boot (1981)", 21.0, "http://upload.wikimedia.org/wikipedia/en/a/a3/Das_boot_ver1.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Oldeuboi (2003)", 6.94, "http://www.winwallpapers.net/w1/2013/12/Oldeuboi-2003-Wallpapers.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Mononoke-hime (1997)", 48.43, "http://4.bp.blogspot.com/-rXY8HEu1PPI/UIKZYX5swtI/AAAAAAAANNw/EaAZi3pSOXU/s1600/Mononoke-hime.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Star Wars: Episode VI - Return of the Jedi (1983)", 33.59, "http://upload.wikimedia.org/wikipedia/en/b/b2/ReturnOfTheJediPoster1983.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Toy Story 3 (2010)", 7.92, "http://ecx.images-amazon.com/images/I/61euyU4feZL.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Once Upon a Time in America (1984)", 48.20, "http://www.74gazette.com/wp-content/themes/rockwell_v1.7.122222/scripts/timthumb.php?src=http://www.74gazette.com/wp-content/uploads/2012/07/61.jpg&w=940&zc=1");
INSERT INTO products (name, price, image_path) VALUES ("Reservoir Dogs (1992)", 42.65, "http://www.impawards.com/1992/posters/reservoir_dogs_ver1.jpg");
INSERT INTO products (name, price, image_path) VALUES ("A Clockwork Orange (1971)", 47.60, "http://41.media.tumblr.com/tumblr_lz4u38Szgs1rn3wkzo1_500.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Taxi Driver (1976)", 32.23, "https://raginggoodfellas.files.wordpress.com/2013/10/taxi-driver_13.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Braveheart (1995)", 47.92, "http://cartelesmix.es/images/CartelesB/braveheart9503.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Requiem for a Dream (2000)", 50.67, "http://static.rogerebert.com/uploads/movie/movie_poster/requiem-for-a-dream-2000/large_muym4jTjdLx7E6as09d1wlC3sOB.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Double Indemnity (1944)", 29.99, "http://upload.wikimedia.org/wikipedia/en/3/35/Double_indemnity.jpg");
INSERT INTO products (name, price, image_path) VALUES ("To Kill a Mockingbird (1962)", 16.75, "http://ecx.images-amazon.com/images/I/51P2YBBDVEL.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Witness for the Prosecution (1957)", 47.89, "http://medialifecrisis.com/files/images/articles/Witness-for-the-Prosecution-1957/Witness-for-the-Prosecution-1957-00.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Lawrence of Arabia (1962)", 22.86, "http://i61.tinypic.com/2qx476d.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Eternal Sunshine of the Spotless Mind (2004)", 6.99, "http://upload.wikimedia.org/wikipedia/en/6/62/Eternal_sunshine_of_the_spotless_mind_ver3.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Full Metal Jacket (1987)", 40.33, "https://thehollywoodexpress.files.wordpress.com/2015/03/wpid-wp-14261062267311.jpeg");
INSERT INTO products (name, price, image_path) VALUES ("The Sting (1973)", 45.31, "http://ecx.images-amazon.com/images/I/5196D3R4RVL.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Singin' in the Rain (1952)", 24.20, "https://365songsblog.files.wordpress.com/2013/09/singin-in-the-rain-half-cut-web-9862.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Ladri di biciclette (1948)", 29.67, "http://img190.imageshack.us/img190/240/ladridibicicletteposter.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Amadeus (1984)", 50.36, "http://thetexastheatre.com/wp-content/uploads/2012/12/3RpcPYW5fkWJmwrng2RpuSfKCv2.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Monty Python and the Holy Grail (1975)", 24.1, "http://lsc.mit.edu/schedule/2014.2q/poster-montypythonandtheholygrail.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Snatch. (2000)", 20.45, "http://s6.postimg.org/6d1s4190x/Snatch2000poster_1.jpg");
INSERT INTO products (name, price, image_path) VALUES ("2001: A Space Odyssey (1968)", 25.43, "http://andygeddon.files.wordpress.com/2012/02/2001.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Kid (1921)", 19.62, "http://upload.wikimedia.org/wikipedia/commons/5/59/CC_The_Kid_1921.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Per qualche dollaro in più (1965)", 49.2, "https://nehovistecose.files.wordpress.com/2013/12/per-qualche-dollaro-in-pic3b9.jpg");
INSERT INTO products (name, price, image_path) VALUES ("L.A. Confidential (1997)", 29.99, "http://greeksubs4free.eu/wp-content/uploads/2014/11/la_confidential_1997.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Rashômon (1950)", 21.79, "http://posterpress.us/uploads/r/rashomon_1950.jpg");
INSERT INTO products (name, price, image_path) VALUES ("All About Eve (1950)", 6.79, "http://ecx.images-amazon.com/images/I/512QQW5Z5DL.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Apartment (1960)", 39.72, "http://www.themoviejerk.co.uk/wp-content/uploads/2012/08/apartment1.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Inglourious Basterds (2009)", 40.90, "http://upload.wikimedia.org/wikipedia/en/c/c3/Inglourious_Basterds_poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Toy Story (1995)", 6.70, "http://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Some Like It Hot (1959)", 42.33, "http://www.doctormacro.com/Images/Posters/S/Poster%20-%20Some%20Like%20it%20Hot%20(1959)_01.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Indiana Jones and the Last Crusade (1989)", 11.62, "http://upload.wikimedia.org/wikipedia/en/f/fc/Indiana_Jones_and_the_Last_Crusade_A.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Treasure of the Sierra Madre (1948)", 46.19, "http://www.turkcealtyazi.org/images/poster/0040897.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Jodaeiye Nader az Simin (2011)", 17.15, "http://3.bp.blogspot.com/-gGjn97z1FFE/UAGTlZ5yNNI/AAAAAAAAAKA/rjxswSfgd38/s1600/a-separation-jodaeiye-nader-az-simin-poster-2011.png");
INSERT INTO products (name, price, image_path) VALUES ("The Third Man (1949)", 49.5, "http://upload.wikimedia.org/wikipedia/en/thumb/2/21/ThirdManUSPoster.jpg/220px-ThirdManUSPoster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Yôjinbô (1961)", 17.42, "http://upload.wikimedia.org/wikipedia/en/8/8b/Yojimbo_(movie_poster).jpg");
INSERT INTO products (name, price, image_path) VALUES ("Batman Begins (2005)", 38.67, "http://vignette4.wikia.nocookie.net/batman/images/1/1e/Batman_Begins_poster6.jpg/revision/latest?cb=20111218145155");
INSERT INTO products (name, price, image_path) VALUES ("Taare Zameen Par (2007)", 33.92, "http://upload.wikimedia.org/wikipedia/en/b/bd/TaareZameenPar.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Metropolis (1927)", 26.89, "http://upload.wikimedia.org/wikipedia/en/0/06/Metropolisposter.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Unforgiven (1992)", 8.72, "http://upload.wikimedia.org/wikipedia/en/4/4e/Unforgiven_2.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Scarface (1983)", 18.12, "http://www.impawards.com/1983/posters/scarface_ver1.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Raging Bull (1980)", 34.96, "http://images4.static-bluray.com/movies/covers/2538_front.jpg");
INSERT INTO products (name, price, image_path) VALUES ("3 Idiots (2009)", 21.79, "http://upload.wikimedia.org/wikipedia/en/d/df/3_idiots_poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Up (2009)", 45.29, "http://www.hdwallpapers.in/walls/pixars_up_2009_movie_official-normal.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Chinatown (1974)", 16.77, "http://posterpress.us/uploads/c/chinatown_1974.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Der Untergang (2004)", 9.67, "http://antiauthor.files.wordpress.com/2009/09/der-untergang-original.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Great Escape (1963)", 21.54, "http://www.film.com/wp-content/uploads/2011/12/936full-the-great-escape-poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Die Hard (1988)", 50.44, "http://upload.wikimedia.org/wikipedia/en/7/7e/Die_hard.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Jagten (2012)", 12.96, "http://phimtorrent.com/wp-content/uploads/2014/07/5027035009025.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Heat (1995)", 26.70, "http://static.cinemagia.ro/img/db/movie/00/05/54/heat-936469l.jpg");
INSERT INTO products (name, price, image_path) VALUES ("On the Waterfront (1954)", 15.35, "http://upload.wikimedia.org/wikipedia/en/f/f4/On_the_Waterfront_poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("El laberinto del fauno (2006)", 22.19, "http://pics.filmaffinity.com/El_laberinto_del_fauno-222302534-large.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Mr. Smith Goes to Washington (1939)", 9.85, "https://stayclassic.files.wordpress.com/2010/05/poster-mr-smith-goes-to-washington_01.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Good Will Hunting (1997)", 31.30, "http://img607.imageshack.us/img607/3327/goodwillhunting1997.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Bridge on the River Kwai (1957)", 16.20, "http://images.static-bluray.com/movies/covers/22250_front.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Tonari no Totoro (1988)", 33.88, "http://www.sinemafilm.org/wp-content/uploads/Tonari-no-Totoro-1988-My-Neighbor-Totoro-1988.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Gold Rush (1925)", 42.15, "http://upload.wikimedia.org/wikipedia/en/thumb/4/4b/Goldrush2.jpg/220px-Goldrush2.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Det sjunde inseglet (1957)", 22.80, "http://www.dvdclassik.com/upload/images/affiches/le-septieme-sceau.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Ikiru (1952)", 47.50, "http://upload.wikimedia.org/wikipedia/commons/3/3a/Ikiru_poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Eskiya (1996)", 47.15, "http://upload.wikimedia.org/wikipedia/en/d/d2/E%C5%9Fk%C4%B1ya.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Ran (1985)", 31.93, "http://static1.squarespace.com/static/5342f393e4b02233d745c04f/53e9584fe4b0a24404145ef1/53e9586be4b0162bed566c8b/1407801480663/ran+poster.png");
INSERT INTO products (name, price, image_path) VALUES ("The Elephant Man (1980)", 22.0, "http://upload.wikimedia.org/wikipedia/en/2/27/TheElephantManposter.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Blade Runner (1982)", 6.13, "https://vokpodcast.files.wordpress.com/2014/01/blade_runner_final_cut.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Smultronstället (1957)", 48.15, "http://img15.nnm.me/d/6/9/9/3/32a07649bebab3ef2ee07d9f87f.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Lock, Stock and Two Smoking Barrels (1998)", 11.97, "http://www.shofonline.org/film/wp-content/uploads/2014/02/shofonline.net_.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The General (1926)", 25.20, "http://image.tmdb.org/t/p/original/7r1k1tn14ktbsAUB1VfcPuINNk7.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Wolf of Wall Street (2013)", 23.67, "http://cdn.collider.com/wp-content/uploads/the-wolf-of-wall-street-blu-ray.jpg");
INSERT INTO products (name, price, image_path) VALUES ("El secreto de sus ojos (2009)", 35.51, "http://pics.filmaffinity.com/El_secreto_de_sus_ojos-862971973-large.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Casino (1995)", 7.84, "https://viewsfromthesofa.files.wordpress.com/2012/07/casino.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Gran Torino (2008)", 49.63, "http://s6.postimg.org/4dn25nmy9/Gran_Torino_locandina3.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Gone Girl (2014)", 11.49, "http://www.teenreads.com/sites/default/files/gone-girl-poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Hauru no ugoku shiro (2004)", 26.54, "http://img.soundtrackcollector.com/movie/large/Hauru_No_Ugoku_Shiro_(2004).jpg");
INSERT INTO products (name, price, image_path) VALUES ("Warrior (2011)", 50.88, "http://i.ytimg.com/vi/kY7HcUACs58/maxresdefault.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Big Lebowski (1998)", 49.89, "http://eatbrie.com/large_posters_files/Biglebowski2.jpg");
INSERT INTO products (name, price, image_path) VALUES ("V for Vendetta (2005)", 30.34, "https://dmoviereview.files.wordpress.com/2012/10/v-for-vendetta-movie-poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Rebecca (1940)", 10.7, "http://upload.wikimedia.org/wikipedia/en/1/16/Rebecca_1940_film_poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Munna Bhai M.B.B.S. (2003)", 43.73, "http://upload.wikimedia.org/wikipedia/en/1/19/Munna_Bhai_M.B.B.S.,_2003_Hindi_film_poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Deer Hunter (1978)", 42.47, "http://www.film.com/wp-content/uploads/2012/03/The-Deer-Hunter-1978-movie-wallpaper.jpg");
INSERT INTO products (name, price, image_path) VALUES ("How to Train Your Dragon (2010)", 13.55, "http://www.movierulz.com/wp-content/uploads/2013/07/How-to-Train-Your-Dragon-2010.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Cool Hand Luke (1967)", 49.90, "http://www.impawards.com/1967/posters/cool_hand_luke_ver6_xlg.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Rang De Basanti (2006)", 34.76, "http://upload.wikimedia.org/wikipedia/en/a/a3/RDB_soundtrack.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Judgment at Nuremberg (1961)", 20.61, "http://upload.wikimedia.org/wikipedia/en/thumb/b/b5/170592-Judgment-at-Nuremberg-Posters.jpg/220px-170592-Judgment-at-Nuremberg-Posters.jpg");
INSERT INTO products (name, price, image_path) VALUES ("It Happened One Night (1934)", 35.86, "http://upload.wikimedia.org/wikipedia/en/thumb/4/40/Gable_ithapponepm_poster.jpg/220px-Gable_ithapponepm_poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("A Wednesday (2008)", 20.17, "http://cdn.gowatchit.com/posters/original/wed.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Fargo (1996)", 38.52, "http://api.ning.com/files/TROotLSon3lXLdleCWWq2LbcENwYCqEdvElmjrGAAQVy0Ky8vSukoVjLSpDkuP*srSa4hZqHLcvxcrI2CwBgTfoSUYO3hAAY/gO0Q7TMuu8PJ9Y736VTgvY02rVD.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Trainspotting (1996)", 13.34, "http://www.cineparadise.com/wp-content/uploads/2014/08/trainspotting-poster-miramax-movie.jpg");
INSERT INTO products (name, price, image_path) VALUES ("A Beautiful Mind (2001)", 33.51, "http://imagizer.imageshack.com/img540/6228/t76BZt.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Gone with the Wind (1939)", 20.50, "http://cdn.movieclips.com/keyart/196570x480.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Into the Wild (2007)", 29.46, "https://applications002.brest-metropole-oceane.fr/VIPBI21/Interligo.web.Front/UploadFiles/images-library/penn_into_the_wild.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Rush (2013/I)", 38.81, "http://cdn.clotureclub.com/wp-content/uploads/2013/09/rush_ver4_xlg.jpg?6b8851");
INSERT INTO products (name, price, image_path) VALUES ("The Maltese Falcon (1941)", 34.34, "http://upload.wikimedia.org/wikipedia/en/9/99/Falconm.JPG");
INSERT INTO products (name, price, image_path) VALUES ("Dial M for Murder (1954)", 48.30, "http://the.hitchcock.zone/files/gallery/org/4655.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Sixth Sense (1999)", 47.86, "http://media.2film.tv/Film/1999/The%20Sixth%20Sense/image01.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Hotel Rwanda (2004)", 19.31, "http://debatefilm.org/ax/pics/images/urltct.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Thing (1982)", 12.74, "http://upload.wikimedia.org/wikipedia/en/c/c1/ThingPoster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Le salaire de la peur (1953)", 27.14, "http://i664.photobucket.com/albums/vv9/francomac123/Travail%20en%20cours/le-salaire-de-la-peur-affiche_269278_2093.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Finding Nemo (2003)", 22.45, "http://img2.wikia.nocookie.net/__cb20130420022756/disney/images/b/ba/Finding_Nemo-_2003.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Incendies (2010)", 38.59, "http://40.media.tumblr.com/tumblr_lvcaeu1Iu71qb1quio1_1280.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Mary and Max (2009)", 25.53, "http://www.impawards.com/2009/posters/mary_and_max_ver2_xlg.jpg");
INSERT INTO products (name, price, image_path) VALUES ("No Country for Old Men (2007)", 18.59, "http://aswedetalksmovies.files.wordpress.com/2012/04/no-country-for-old-men.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Kill Bill: Vol. 1 (2003)", 22.47, "http://www.moviepdb.net/posters/kill-bill-vol-1-original7.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Butch Cassidy and the Sundance Kid (1969)", 25.48, "http://vignette1.wikia.nocookie.net/scratchpad/images/b/bf/Butch_cassidy_and_the_sundance_kid_xlg.jpg/revision/latest?cb=20130829032303");
INSERT INTO products (name, price, image_path) VALUES ("Life of Brian (1979)", 8.86, "http://professormortis.files.wordpress.com/2012/09/life-of-brian.jpeg");
INSERT INTO products (name, price, image_path) VALUES ("Platoon (1986)", 43.49, "http://www.historybanter.com/wp-content/uploads/2013/07/platoon_1986.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Network (1976)", 40.37, "http://hqdesktopwallpapers.net/wp-content/uploads/2014/04/1919__network_(1976)movie_.jpg");
INSERT INTO products (name, price, image_path) VALUES ("12 Years a Slave (2013)", 16.1, "https://agcrump.files.wordpress.com/2013/10/12-years-a-slave-movie.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Touch of Evil (1958)", 15.99, "https://bloodymurder.files.wordpress.com/2011/10/poster-touch-of-evil_02.jpg");
INSERT INTO products (name, price, image_path) VALUES ("There Will Be Blood (2007)", 16.6, "http://ccmoviereviews.com/wp-content/uploads/2014/05/Therewillbeblood.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Les diaboliques (1955)", 43.66, "http://upload.wikimedia.org/wikipedia/en/thumb/3/37/Lesdiaboliquesposter.jpg/225px-Lesdiaboliquesposter.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Princess Bride (1987)", 10.87, "https://lunkiandsika.files.wordpress.com/2011/10/the-princess-bride-1987-poster-01.png");
INSERT INTO products (name, price, image_path) VALUES ("Annie Hall (1977)", 25.57, "http://up.vbiran.ir/uploads/8754142491115136392_1812__annie_hall_(1977)movie_.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Stand by Me (1986)", 9.24, "http://images2.static-bluray.com/movies/covers/19417_front.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Grand Budapest Hotel (2014)", 22.42, "http://imovieshd.net/wp-content/uploads/2014/12/the-grand-budapest-hotel-2014-large-picture.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Ben-Hur (1959)", 50.80, "http://upload.wikimedia.org/wikipedia/commons/7/74/Ben_hur_1959_poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("In the Name of the Father (1993)", 28.50, "http://image.tmdb.org/t/p/w500/wRzSR6tW22tFpFN68YpAZKSiZJV.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Amores perros (2000)", 7.72, "http://static.cinemagia.ro/img/db/movie/00/16/85/amores-perros-112645l.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Les quatre cents coups (1959)", 18.73, "http://aworldoffilm.files.wordpress.com/2013/12/400blowsposter04.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Sin City (2005)", 34.35, "http://imovieshd.net/wp-content/uploads/2015/02/11174189_800.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Boyhood (2014/I)", 27.5, "https://germanfilmguy.files.wordpress.com/2014/10/boyhood.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Million Dollar Baby (2004)", 5.76, "https://refractionsfilm.files.wordpress.com/2013/02/million_dollar_baby_2004_poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Hachi: A Dog's Tale (2009)", 26.97, "http://moviemassala.com/wp-content/uploads/2014/03/h.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Grapes of Wrath (1940)", 20.95, "http://themotionpictures.files.wordpress.com/2012/10/gw4.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Persona (1966)", 34.47, "http://image.toutlecine.com/photos/p/e/r/persona-1966-01-g.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Wizard of Oz (1939)", 42.21, "http://quoteshub.weebly.com/uploads/1/2/7/8/12780665/5690865_orig.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Best Years of Our Lives (1946)", 19.90, "http://www.filmsite.org/posters/besty3.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Guardians of the Galaxy (2014)", 37.0, "https://paulselluloid.files.wordpress.com/2014/08/guardians_of_the_galaxy__2014____theatrical_poster_by_camw1n-d7dohkp.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Dil Chahta Hai (2001)", 45.85, "http://img7.imageshack.us/img7/2545/dilchahtahai2001.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Kaze no tani no Naushika (1984)", 47.29, "https://timneath.files.wordpress.com/2013/04/nausicaacc88-of-the-valley-of-the-wind-1984.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Gandhi (1982)", 37.62, "http://filmfanatic.org/reviews/wp-content/uploads/2006/09/Gandhi-Poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Avengers (2012)", 14.58, "http://api.ning.com/files/L67J4KB8XT3IjVssf9Bgh0lSKMlafQTNNpnYOIP6UxC-bOpYZiiBVfDiJIYV7rh5Z-EcVLoHWweYobsHNcAB1tTL-ArEo5vj/theavengersmovie1.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Bourne Ultimatum (2007)", 32.70, "http://static.rogerebert.com/uploads/movie/movie_poster/the-bourne-ultimatum-2007/large_fHho6JYYY0nRcETWSoeI19iZsNF.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Donnie Darko (2001)", 33.35, "http://upload.wikimedia.org/wikipedia/en/d/db/Donnie_Darko_poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Imitation Game (2014)", 29.5, "http://upload.wikimedia.org/wikipedia/en/5/5e/The_Imitation_Game_poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Strangers on a Train (1951)", 18.41, "http://the.hitchcock.zone/files/captures/4605_front.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Shutter Island (2010)", 24.18, "http://themotionpictures.files.wordpress.com/2012/06/si1.jpg");
INSERT INTO products (name, price, image_path) VALUES ("8½ (1963)", 21.35, "http://s3.amazonaws.com/criterion-production/release_boxshots/191-9729ad5f91251bc2fd759186c4586d0c/140_box_348x490_original.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Mou gaan dou (2002)", 37.80, "http://static3.opensubtitles.org/gfx/thumbs/4/6/5/8/0338564.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Stalker (1979)", 21.58, "http://cdn8.openculture.com/wp-content/uploads/2014/11/andrei-tarkovsky-stalker-1979.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Twelve Monkeys (1995)", 29.85, "http://posterpress.us/uploads/t/twelve_monkeys_1995.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Jaws (1975)", 11.78, "http://upload.wikimedia.org/wikipedia/en/e/eb/JAWS_Movie_poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Before Sunrise (1995)", 5.3, "http://www.likedreviews.com/wp-content/uploads/2015/02/52.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Lagaan: Once Upon a Time in India (2001)", 35.33, "http://www.matthiasgiger.ch/movies/front_large/Lagaan%20front.jpg");
INSERT INTO products (name, price, image_path) VALUES ("High Noon (1952)", 6.86, "http://upload.wikimedia.org/wikipedia/en/5/54/High_Noon_poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Terminator (1984)", 27.39, "http://upload.wikimedia.org/wikipedia/en/7/70/Terminator1984movieposter.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Groundhog Day (1993)", 23.52, "http://spi4uk.itvnet.lv/upload2/articles/68/681832/images/_origin_Fakti-par-filmu-1.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Fanny och Alexander (1982)", 43.13, "https://ydre1952.files.wordpress.com/2012/06/fanny_och_alexander_82_a.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Notorious (1946)", 5.47, "http://static.rogerebert.com/uploads/movie/movie_poster/notorious-1946/large_7ll5OJRWDamfVLPnXKKhHWWoHz0.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The King's Speech (2010)", 49.55, "http://upload.wikimedia.org/wikipedia/en/a/a0/Kings_speech_ver3.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Harry Potter and the Deathly Hallows: Part 2 (2011)", 23.56, "http://www.assignmentx.com/wp-content/uploads/2011/11/HARRY-POTTER-AND-THE-DEATHLY-HALLOWS-PART-2.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Gangs of Wasseypur (2012)", 25.15, "http://upload.wikimedia.org/wikipedia/en/6/6a/Gangs_of_Wasseypur_poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Yip Man (2008)", 8.64, "http://filmtipps.tv/wp-content/uploads/2014/03/ip-man.jpeg");
INSERT INTO products (name, price, image_path) VALUES ("Monsters, Inc. (2001)", 50.82, "http://moviebyte.com/?ACT=29&f=monstruos_sa_2001_3.jpg&fid=15&d=1684&");
INSERT INTO products (name, price, image_path) VALUES ("Rocky (1976)", 30.21, "http://professormortis.files.wordpress.com/2012/09/rocky-half-sheet.jpeg");
INSERT INTO products (name, price, image_path) VALUES ("La battaglia di Algeri (1966)", 40.57, "http://www.orgs.bucknell.edu/hilltop/new%20stuff/battle%20of%20algiers.jpg");
INSERT INTO products (name, price, image_path) VALUES ("La haine (1995)", 19.56, "http://upload.wikimedia.org/wikipedia/en/3/30/Haine.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Dog Day Afternoon (1975)", 44.68, "http://4.bp.blogspot.com/-rFznlSLBxcU/VObpX2e2dKI/AAAAAAAAHTw/v1uok1euv4s/s1600/Dog%2BDay%2BAfternoon%2B1975%2Bdvd.png");
INSERT INTO products (name, price, image_path) VALUES ("The Night of the Hunter (1955)", 34.77, "https://image.tmdb.org/t/p/original/2bBGFSrnTg1AFhjHoczbfPnb9D4.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Salinui chueok (2003)", 37.68, "http://image.tmdb.org/t/p/original/xlX76DGRRWvbLkY1pXbSBYlX7lD.jpg");
INSERT INTO products (name, price, image_path) VALUES ("X-Men: Days of Future Past (2014)", 43.55, "http://upload.wikimedia.org/wikipedia/en/0/0c/X-Men_Days_of_Future_Past_poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Barry Lyndon (1975)", 33.51, "http://posterpress.us/uploads/b/barry_lyndon_1975.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Per un pugno di dollari (1964)", 49.1, "http://www.ossinotizie.it/wp-content/uploads/2014/09/Per-un-pugno-di-dollari-Locandina.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Truman Show (1998)", 39.11, "http://upload.wikimedia.org/wikipedia/en/c/cd/Trumanshow.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Pirates of the Caribbean: The Curse of the Black Pearl (2003)", 29.20, "http://upload.wikimedia.org/wikipedia/en/0/0e/Pirates_of_the_Caribbean_movie.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Who's Afraid of Virginia Woolf? (1966)", 43.41, "http://www.dvdsreleasedates.com/covers/whos-afraid-of-virginia-woolf-dvd-cover-77.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Tenkû no shiro Rapyuta (1986)", 7.34, "http://www.agluu.it/locandine_film/20131030185919.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Kingsman: The Secret Service (2014)", 46.57, "http://cdn1-www.comingsoon.net/assets/uploads/2014/05/file_118522_1_kingsmanposterlarge.jpg");
INSERT INTO products (name, price, image_path) VALUES ("La strada (1954)", 16.57, "http://static1.squarespace.com/static/52d46da1e4b093a3faf3e1fc/t/54b9bdd0e4b069dab25fa076/1421458898190/");
INSERT INTO products (name, price, image_path) VALUES ("Jurassic Park (1993)", 33.6, "http://img4.wikia.nocookie.net/__cb20141015011537/jurassicpark/images/c/ce/JP-MoviePoster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Help (2011)", 33.61, "https://image.tmdb.org/t/p/original/9I1MpxNQ59XJ0sQ8yBIa7Vrrgel.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Big Sleep (1946)", 46.69, "http://www.filmsite.org/posters/bigs2.gif");
INSERT INTO products (name, price, image_path) VALUES ("Roman Holiday (1953)", 26.92, "http://cdn.300mbmovies4u.com/imgs/romanholiday.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Graduate (1967)", 41.55, "https://entertainmentblur.files.wordpress.com/2010/10/the-graduate.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Papillon (1973)", 40.45, "http://covers.box3.net/newsimg/dvdmov/max1108990112-frontback-cover.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Prisoners (2013)", 30.99, "http://upload.wikimedia.org/wikipedia/en/thumb/6/63/Prisoners2013Poster.jpg/220px-Prisoners2013Poster.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Beauty and the Beast (1991)", 14.84, "http://aretheyoldenough.com/wp-content/uploads/2014/12/beauty_and_the_beast_1991.jpg");
INSERT INTO products (name, price, image_path) VALUES ("The Hustler (1961)", 13.76, "http://image.tmdb.org/t/p/original/t6ffSUIrfjx5V5hqzvwdwjq9yWB.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Le samouraï (1967)", 19.3, "http://i664.photobucket.com/albums/vv9/francomac123/Travail%20en%20cours/Travail%20par%20albums%202/Melville-1967-Le%20Samourai/samourai_aff_1.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Akira (1988)", 25.19, "http://wrongsideoftheart.com/wp-content/gallery/posters-a/akira_poster_03.jpg");
INSERT INTO products (name, price, image_path) VALUES ("Before Sunset (2004)", 8.1, "http://fullhdwp.com/images/wallpapers/before_sunset__2004__ethan_hawke__julie_delpy-wallpaper.jpg");
